In [3]:
import numpy as np

In [7]:
a = np.array([
    [10.5, 11.1,],
    [12.8, 13.5,]
])    

b = np.array([
    [1.2],
    [2.3],
])

In [8]:
np.dot(a, b)

array([[38.13],
       [46.41]])

In [3]:
import numpy as np
import time

size = 5

# Matrix A: A[i][j] = i + j
A = np.fromfunction(lambda i, j: i + j, (16, 28*28), dtype=float)

# Matrix B: B[i][j] = i * j (you can use any pattern here)
B = np.fromfunction(lambda i, j: i * j, (28*28, 1), dtype=float)

# Time the multiplication
start = time.time()

result = A @ B  # Matrix × Matrix multiplication

end = time.time()
elapsed = (end - start) * 1e6  # microseconds

print(f"Time taken for {size}x{size} * {size}x{size} multiplication: {elapsed:.2f} µs")

# Show result matrix
print("Result matrix:")
print(result)


Time taken for 5x5 * 5x5 multiplication: 0.00 µs
Result matrix:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [14]:
import numpy as np

def generate_tensor(rows, cols, seed=42):
    rng = np.random.Generator(np.random.PCG64(seed))
    data = rng.random((rows, cols))  # Uniform [0.0, 1.0)
    return data

# Example
tensor = generate_tensor(3, 3, seed=42)
print(tensor)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
